### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rieje** [dustymabe/virtscripts#1]
Hi, came across this [post of yours](https://dustymabe.com/2015/01/11/qemu-img-backing-files-a-poor-mans-snapshotrollback/). I was curious if you still find working with QEMU backing files to be ideal a decade later or if e.g. working with libvirt external snapshots are preferable. 

Thanks!

**Comment by dustymabe** [comment]
if you are using libvirt you can just refer to the original disk image as a backing store and it does the same thing:

```
virt-install --disk backing_store=/path/to/original/disk.img,size=20 ...
```
